<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>frontend-manage-secrets</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.DevServer" Version="9.0.5" PrivateAssets="all" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="9.0.7" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="9.0.8" />
    <PackageReference Include="MudBlazor" Version="8.9.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.12.1" />
    <PackageReference Include="EPPlus" Version="6.2.4" />
  </ItemGroup>

  <!-- Copy appsettings.json vào wwwroot để Blazor WASM có thể đọc -->
  <Target Name="CopyAppSettingsToWwwroot" AfterTargets="Build">
    <Copy SourceFiles="$(ProjectDir)appsettings.json" DestinationFolder="$(ProjectDir)wwwroot\" Condition="Exists('$(ProjectDir)appsettings.json')" />
    <Copy SourceFiles="$(ProjectDir)appsettings.Development.json" DestinationFolder="$(ProjectDir)wwwroot\" Condition="Exists('$(ProjectDir)appsettings.Development.json')" />
  </Target>

  <ItemGroup>
    <Folder Include="DTOs\Mapp\" />
    <Folder Include="Pages\AcademicAffairs\" />
    <Folder Include="Pages\Admin\" />
  </ItemGroup>


</Project>
