<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AspNetCoreRateLimit" Version="5.0.0" />
        <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="12.0.1" />
        <PackageReference Include="BCrypt.Net-Next" Version="4.0.3" />
        <PackageReference Include="Confluent.Kafka" Version="2.11.0" />
        <PackageReference Include="EPPlus" Version="7.7.0" />
        <PackageReference Include="iText7" Version="9.1.0" />
        <PackageReference Include="MailKit" Version="4.11.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.0" />
        <PackageReference Include="Microsoft.AspNetCore.Authorization" Version="9.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.4" />
        <PackageReference Include="Microsoft.AspNetCore.ResponseCompression" Version="2.3.0" />
        <PackageReference Include="Microsoft.AspNetCore.SignalR" Version="1.2.0" />
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
          <PrivateAssets>all</PrivateAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" Version="9.0.2" />
        <PackageReference Include="Microsoft.IdentityModel.Tokens" Version="8.13.0" />
        <PackageReference Include="QuestPDF" Version="2025.1.7" />
        <PackageReference Include="RabbitMQ.Client" Version="6.8.1" />
        <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
        <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
        <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
        <PackageReference Include="SharpZipLib" Version="1.4.2" />
        <PackageReference Include="StackExchange.Redis" Version="2.8.58" />
        <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.13.0" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\audio\helloim-going-to-talk-about-b1672025838.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\audio\What_are_you_going_to_do.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\css\admin\ManageExam.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\admin\MessageBox.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\admin\monitor\global.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\admin\monitor\style.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\admin\monitor\styleguide.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\app.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\exam\reset.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\exam\style.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\info\info.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\login\login.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\main_layout\notauthorize.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\monitor.css" />
      <_ContentIncludedByDefault Remove="wwwroot\css\Result\style.css" />
      <_ContentIncludedByDefault Remove="wwwroot\jquery\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPM003\9f92ab68-54e9-4efe-af23-6f7f59e68373\9f92ab68-54e9-4efe-af23-6f7f59e68373.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPM004\9f92ab68-54e9-4efe-af23-6f7f59e68373\9f92ab68-54e9-4efe-af23-6f7f59e68373.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPM002\9f92ab68-54e9-4efe-af23-6f7f59e68373\9f92ab68-54e9-4efe-af23-6f7f59e68373.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN1\31371555-afe8-45ec-b629-7450801efba7\31371555-afe8-45ec-b629-7450801efba7.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN1\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\4ab18c17-8193-43ce-9b4a-5141ae1272ff.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN1\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\6529febd-3097-4673-bb39-792b73ce8dc9.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN9\31371555-afe8-45ec-b629-7450801efba7\31371555-afe8-45ec-b629-7450801efba7.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN9\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\4ab18c17-8193-43ce-9b4a-5141ae1272ff.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN9\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\6529febd-3097-4673-bb39-792b73ce8dc9.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN11\31371555-afe8-45ec-b629-7450801efba7\31371555-afe8-45ec-b629-7450801efba7.xml" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN11\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\4ab18c17-8193-43ce-9b4a-5141ae1272ff.mp3" />
      <_ContentIncludedByDefault Remove="wwwroot\EPZ\CNPMNN11\31371555-afe8-45ec-b629-7450801efba7\Data\Audio\6529febd-3097-4673-bb39-792b73ce8dc9.mp3" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Logs\" />
      <Folder Include="wwwroot\EPZ\" />
    </ItemGroup>

</Project>